### ISSUE TITLE
Demopage or lib bug

### ISSUE THREAD

**Issue by macik** [charliegeiger89/Scrolld.js#2]
Tested on demo page.

After multiple clicking on «Going up?» button had a weird flicking effects on scroll down with mouse wheel.

See it on video
http://www.youtube.com/watch?v=xK8fmOFq_Ck

**Comment by charliegeiger89** [comment]
I know exactly what that is. It is actually not a bug of any sort but rather a quirk of the jQuery animate parameter.

First off, that back to top button is actually running on it's own tiny piece of script and is not using Scrolld.js at all. Even though it has nothing to do with the plugin I think it is important to explain what is going on because you might experience it at sometime with the plugin.

The issue you have documented is due to the speed parameter of the animate scrollTop: 0 method. Basically what is happening is I set a period of 1500 milliseconds for the method to complete by, and until that period is passed it will attempt to re-adjust back to scrollTop: 0. The 'flickering' that you are seeing is actually the page scrolling back to the top, it is counteracting your scrolling down by scrolling to the top. Also, when you click multiple times it can cue up the method by restarting the 1500 millisecond period. Since the method itself is calling on the use of the scroll function you cannot simply tell it to stop scrolling if the scrollbar moves. You actually have to set up an additional event listener that will overlook the scrollTop scrolling and only listen for a user scroll.  

I went and found a working solution to this issue, it was posted back in 2010 but still works. You can find it here,  http://stackoverflow.com/questions/2834667/how-can-i-differentiate-a-manual-scroll-via-mousewheel-scrollbar-from-a-javasc  

There is a cost / benefit to using it though. Say a user on a touchscreen who might accidentally bump their finger, if they do that it will immediately stop any scrolling in process. Same with desktop browsing, if you scroll at all while it is already scrolling it will immediately kill the scrolling. Then you are left with a probably more confused user than having it flicker for a second. The other option to prevent this would be to hide the scroll to top button until further down the page where it becomes more necessary to use.

Another note is that the issue is actually present for any scrolling if you set your scroll speed to be a long period. Say you set the speed to 5 seconds, unless the page is extremely long the scrolling will be very slow and any user scrolling during that time will result in the same visual 'flickering' or stuttering that is more easily noticed with scrolling to the top. The faster the speed ( lower number ), the less likely it is that your user will experience the flickering. The easing function can also play a role, if you use an easing function that spikes rapidly and spends the majority of its time at the end of the animation it will leave a larger window / period of time for the user to experience the flickering.

Let me know if you need further explanation!
